# Define los servicios gestionados por Render
services:
  # Define tu servicio web API
  - type: web # Tipo de servicio (web, worker, etc.)
    name: api-asistente # El nombre de tu servicio en Render
    env: docker # ¡Clave! Especifica que el entorno es Docker
    repo: https://github.com/Ubikua-Git/ubikua_agenteiad # La URL de tu repositorio (verifica si es esta)
    branch: main # La rama que Render debe desplegar
    dockerfilePath: ./Dockerfile # Ruta al Dockerfile dentro del repositorio
    # region: frankfurt # Opcional: Especifica la región si es necesario (ej. Oregon, Frankfurt)
    plan: free # Especifica el plan de instancia (ej. starter, standard, etc. - verifica tu plan actual)
    envVars: # Define las variables de entorno necesarias
      - key: PYTHON_VERSION # Opcional, pero buena práctica
        value: '3.11'
      # IMPORTANTE: Las claves API se declaran aquí pero sus valores
      # se seguirán tomando de forma segura desde el Dashboard de Render.
      # 'sync: false' evita que este archivo sobrescriba los valores del dashboard.
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CX
        sync: false
    # El comando para iniciar tu aplicación una vez construido el contenedor
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    # healthCheckPath: /health # Opcional: si tienes un endpoint de health check